// <auto-generated />
using System;
using Dram_Capstone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dram_Capstone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dram_Capstone.Models.FragrantFlavor", b =>
                {
                    b.Property<int>("FragrantFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("FragrantFlavor_Id");

                    b.ToTable("FragrantFlavor");

                    b.HasData(
                        new
                        {
                            FragrantFlavor_Id = 1,
                            Name = "Lavender"
                        },
                        new
                        {
                            FragrantFlavor_Id = 2,
                            Name = "Acetone"
                        },
                        new
                        {
                            FragrantFlavor_Id = 3,
                            Name = "Pine"
                        },
                        new
                        {
                            FragrantFlavor_Id = 4,
                            Name = "Honey"
                        },
                        new
                        {
                            FragrantFlavor_Id = 5,
                            Name = "Beeswax"
                        },
                        new
                        {
                            FragrantFlavor_Id = 6,
                            Name = "Rose"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.FruityFlavor", b =>
                {
                    b.Property<int>("FruityFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("FruityFlavor_Id");

                    b.ToTable("FruityFlavor");

                    b.HasData(
                        new
                        {
                            FruityFlavor_Id = 1,
                            Name = "Apple"
                        },
                        new
                        {
                            FruityFlavor_Id = 2,
                            Name = "Fig"
                        },
                        new
                        {
                            FruityFlavor_Id = 3,
                            Name = "Cherry"
                        },
                        new
                        {
                            FruityFlavor_Id = 4,
                            Name = "Orange"
                        },
                        new
                        {
                            FruityFlavor_Id = 5,
                            Name = "Marmalade"
                        },
                        new
                        {
                            FruityFlavor_Id = 6,
                            Name = "Canned Peaches"
                        },
                        new
                        {
                            FruityFlavor_Id = 7,
                            Name = "Raisins"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.GrainyFlavor", b =>
                {
                    b.Property<int>("GrainyFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("GrainyFlavor_Id");

                    b.ToTable("GrainyFlavor");

                    b.HasData(
                        new
                        {
                            GrainyFlavor_Id = 1,
                            Name = "Coffee"
                        },
                        new
                        {
                            GrainyFlavor_Id = 2,
                            Name = "Dried Hops"
                        },
                        new
                        {
                            GrainyFlavor_Id = 3,
                            Name = "Malted Milk"
                        },
                        new
                        {
                            GrainyFlavor_Id = 4,
                            Name = "Breakfast Cereal"
                        },
                        new
                        {
                            GrainyFlavor_Id = 5,
                            Name = "Biscuits"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.GrassyFlavor", b =>
                {
                    b.Property<int>("GrassyFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("GrassyFlavor_Id");

                    b.ToTable("GrassyFlavor");

                    b.HasData(
                        new
                        {
                            GrassyFlavor_Id = 1,
                            Name = "Cut Grass"
                        },
                        new
                        {
                            GrassyFlavor_Id = 2,
                            Name = "Green Sticks"
                        },
                        new
                        {
                            GrassyFlavor_Id = 3,
                            Name = "Tobacco"
                        },
                        new
                        {
                            GrassyFlavor_Id = 4,
                            Name = "Dried Herbs"
                        },
                        new
                        {
                            GrassyFlavor_Id = 5,
                            Name = "Dried Tea Leaf"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.OffNoteFlavor", b =>
                {
                    b.Property<int>("OffNoteFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("OffNoteFlavor_Id");

                    b.ToTable("OffNoteFlavor");

                    b.HasData(
                        new
                        {
                            OffNoteFlavor_Id = 1,
                            Name = "Earthy"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 2,
                            Name = "Roast Meat"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 3,
                            Name = "Fatty"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 4,
                            Name = "Leather"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 5,
                            Name = "Struck Matches"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 6,
                            Name = "Rusty"
                        },
                        new
                        {
                            OffNoteFlavor_Id = 7,
                            Name = "Vinegar"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.PeatyFlavor", b =>
                {
                    b.Property<int>("PeatyFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("PeatyFlavor_Id");

                    b.ToTable("PeatyFlavor");

                    b.HasData(
                        new
                        {
                            PeatyFlavor_Id = 1,
                            Name = "Shellfish"
                        },
                        new
                        {
                            PeatyFlavor_Id = 2,
                            Name = "Brine"
                        },
                        new
                        {
                            PeatyFlavor_Id = 3,
                            Name = "Seaweed"
                        },
                        new
                        {
                            PeatyFlavor_Id = 4,
                            Name = "Iodine"
                        },
                        new
                        {
                            PeatyFlavor_Id = 5,
                            Name = "Mouthwash"
                        },
                        new
                        {
                            PeatyFlavor_Id = 6,
                            Name = "Peat Smoke"
                        },
                        new
                        {
                            PeatyFlavor_Id = 7,
                            Name = "Smoked Salmon"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.Review", b =>
                {
                    b.Property<int>("Review_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FragrantFlavor_Id");

                    b.Property<int>("FruityFlavor_Id");

                    b.Property<int>("GrainyFlavor_Id");

                    b.Property<int>("GrassyFlavor_Id");

                    b.Property<int>("OffNoteFlavor_Id");

                    b.Property<int>("PeatyFlavor_Id");

                    b.Property<int>("ReviewScore");

                    b.Property<string>("TastingNotes");

                    b.Property<int>("WineyFlavor_Id");

                    b.Property<int>("WoodyFlavor_Id");

                    b.HasKey("Review_Id");

                    b.HasIndex("FragrantFlavor_Id");

                    b.HasIndex("FruityFlavor_Id");

                    b.HasIndex("GrainyFlavor_Id");

                    b.HasIndex("GrassyFlavor_Id");

                    b.HasIndex("OffNoteFlavor_Id");

                    b.HasIndex("PeatyFlavor_Id");

                    b.HasIndex("WineyFlavor_Id");

                    b.HasIndex("WoodyFlavor_Id");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            Review_Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FragrantFlavor_Id = 1,
                            FruityFlavor_Id = 1,
                            GrainyFlavor_Id = 1,
                            GrassyFlavor_Id = 1,
                            OffNoteFlavor_Id = 1,
                            PeatyFlavor_Id = 1,
                            ReviewScore = 95,
                            TastingNotes = "lots of alcohol, very smokey, good neat",
                            WineyFlavor_Id = 1,
                            WoodyFlavor_Id = 1
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.Whiskey", b =>
                {
                    b.Property<int>("WhiskeyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Distillery")
                        .IsRequired();

                    b.Property<bool>("Favorite");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("Review_Id");

                    b.Property<string>("UserId");

                    b.Property<string>("User_Id")
                        .IsRequired();

                    b.HasKey("WhiskeyId");

                    b.HasIndex("Review_Id");

                    b.HasIndex("UserId");

                    b.ToTable("Whiskey");

                    b.HasData(
                        new
                        {
                            WhiskeyId = 1,
                            Distillery = "Ardbeg",
                            Favorite = false,
                            Name = "10 year",
                            Review_Id = 1,
                            User_Id = "85ee9ee5-ecbd-40d8-a31e-a5c20c59fa1c"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.WineyFlavor", b =>
                {
                    b.Property<int>("WineyFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("WineyFlavor_Id");

                    b.ToTable("WineyFlavor");

                    b.HasData(
                        new
                        {
                            WineyFlavor_Id = 1,
                            Name = "Almond"
                        },
                        new
                        {
                            WineyFlavor_Id = 2,
                            Name = "Cream"
                        },
                        new
                        {
                            WineyFlavor_Id = 3,
                            Name = "Butter"
                        },
                        new
                        {
                            WineyFlavor_Id = 4,
                            Name = "Chocolate"
                        },
                        new
                        {
                            WineyFlavor_Id = 5,
                            Name = "Olive"
                        },
                        new
                        {
                            WineyFlavor_Id = 6,
                            Name = "Sherry"
                        },
                        new
                        {
                            WineyFlavor_Id = 7,
                            Name = "Port"
                        },
                        new
                        {
                            WineyFlavor_Id = 8,
                            Name = "Red Wine"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.WoodyFlavor", b =>
                {
                    b.Property<int>("WoodyFlavor_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("WoodyFlavor_Id");

                    b.ToTable("WoodyFlavor");

                    b.HasData(
                        new
                        {
                            WoodyFlavor_Id = 1,
                            Name = "Caramel"
                        },
                        new
                        {
                            WoodyFlavor_Id = 2,
                            Name = "Creme Brulee"
                        },
                        new
                        {
                            WoodyFlavor_Id = 3,
                            Name = "Syrup"
                        },
                        new
                        {
                            WoodyFlavor_Id = 4,
                            Name = "Clove"
                        },
                        new
                        {
                            WoodyFlavor_Id = 5,
                            Name = "Pepper"
                        },
                        new
                        {
                            WoodyFlavor_Id = 6,
                            Name = "Cigar Box"
                        },
                        new
                        {
                            WoodyFlavor_Id = 7,
                            Name = "Ginger"
                        },
                        new
                        {
                            WoodyFlavor_Id = 8,
                            Name = "Liquorice"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Dram_Capstone.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "85ee9ee5-ecbd-40d8-a31e-a5c20c59fa1c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "61d85423-79ec-45c4-97b3-d739610e83cc",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELkBC92YoaldxZrc4gjBDv/bEvmSiS9BLfSVJ7lyZZ7P39bHnBuNdP7/iH7nroWv+A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e386b2a-b41b-4ab3-b26f-62b94f9cfd51",
                            TwoFactorEnabled = false,
                            FirstName = "admin",
                            LastName = "admin"
                        });
                });

            modelBuilder.Entity("Dram_Capstone.Models.Review", b =>
                {
                    b.HasOne("Dram_Capstone.Models.FragrantFlavor", "FragrantFlavor")
                        .WithMany()
                        .HasForeignKey("FragrantFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.FruityFlavor", "FruityFlavor")
                        .WithMany()
                        .HasForeignKey("FruityFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.GrainyFlavor", "GrainyFlavor")
                        .WithMany()
                        .HasForeignKey("GrainyFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.GrassyFlavor", "GrassyFlavor")
                        .WithMany()
                        .HasForeignKey("GrassyFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.OffNoteFlavor", "OffNoteFlavor")
                        .WithMany()
                        .HasForeignKey("OffNoteFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.PeatyFlavor", "PeatyFlavor")
                        .WithMany()
                        .HasForeignKey("PeatyFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.WineyFlavor", "WineyFlavor")
                        .WithMany()
                        .HasForeignKey("WineyFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dram_Capstone.Models.WoodyFlavor", "WoodyFlavor")
                        .WithMany()
                        .HasForeignKey("WoodyFlavor_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dram_Capstone.Models.Whiskey", b =>
                {
                    b.HasOne("Dram_Capstone.Models.Review", "Review")
                        .WithMany()
                        .HasForeignKey("Review_Id");

                    b.HasOne("Dram_Capstone.Models.ApplicationUser", "User")
                        .WithMany("Whiskeys")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
